/**
 * MJ Secure Messaging — Server bootstrap.
 *
 * Import this package and call LoadSecureMessagingServer() from the host API
 * (an MJAPI host) so every @RegisterClass decorator fires (entities, actions, the
 * Secure Web communication provider, eSignature drivers) and the GraphQL
 * resolvers are discoverable via RESOLVER_PATHS.
 */
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LogStatus } from '@memberjunction/core';
import { setMessageNotifier } from '@mj-biz-apps/secure-messaging-core';
import { secureMessagingNotifier } from './services/SecureMessagingNotifier.js';

// Generated entity + action subclasses (fire @RegisterClass on import).
import { LoadGeneratedEntities } from '@mj-biz-apps/secure-messaging-entities';
import '@mj-biz-apps/secure-messaging-actions';

// Core services (PortalAuthService, stores, config) — imported so any registrations fire.
import '@mj-biz-apps/secure-messaging-core';

// Secure Web communication provider (auto-registers via @RegisterClass on import).
import './services/SecureWebCommunicationProvider.js';

// Server middleware that mounts the portal REST API pre-auth (auto-registers via @RegisterClass).
import './SecureMessagingMiddleware.js';

// E-signature provider drivers (DocuSign / PandaDoc / Dropbox Sign). Each package's
// @RegisterClass(BaseSignatureProvider, '<DriverKey>') side-effect lets the MJ
// SignatureEngine resolve the driver named by an MJ: Signature Provider's ServerDriverKey.
import '@memberjunction/esignature-docusign';
import '@memberjunction/esignature-pandadoc';
import '@memberjunction/esignature-dropboxsign';

// Generated class-registrations manifest — static anchor so the host bundler can't
// tree-shake our @RegisterClass classes (regenerated by the `prebuild` mj codegen manifest).
import { CLASS_REGISTRATIONS } from './generated/class-registrations-manifest.js';
export { CLASS_REGISTRATIONS } from './generated/class-registrations-manifest.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

/** Resolver paths for the host's TypeGraphQL schema build (generated + any custom resolvers). */
export const RESOLVER_PATHS: string[] = [
  resolve(__dirname, 'resolvers/*.js'),
  resolve(__dirname, 'generated/*.js'),
];

/**
 * Bootstrap entry point. Static imports above ensure all @RegisterClass decorators fire;
 * this function is the explicit anchor the host calls (and prevents tree-shaking).
 */
export function LoadSecureMessagingServer(): void {
  LoadGeneratedEntities();
  void CLASS_REGISTRATIONS; // anchor the manifest so registrations are never tree-shaken
  // Wire the notify hook: outbound messages email the contact a magic-link nudge (PRD §9).
  // No-ops gracefully when SECURE_MESSAGING_EMAIL_PROVIDER / FROM_EMAIL aren't configured.
  setMessageNotifier(secureMessagingNotifier);
  LogStatus('MJ Secure Messaging: Server bootstrap loaded.');
}

// Public server surface for hosts/embedders:
// Secure Web communication provider class
export { SecureWebCommunicationProvider } from './services/SecureWebCommunicationProvider.js';
// Express router (mounts the portal REST API)
export { createSecureMessagingRouter, mountSecureMessagingRoutes } from './routes.js';
// Server middleware that auto-mounts the portal REST API into MJAPI (pre-auth)
export { SecureMessagingMiddleware, SECURE_MESSAGING_BASE_PATH } from './SecureMessagingMiddleware.js';
// Middleware types
export type { PortalRequest } from './handlers/middleware.js';
