import { LogStatus } from '@memberjunction/core';

// Pre-built class-registrations manifest (generated by `mj codegen manifest`). The static
// imports it contains prevent the host bundler from tree-shaking our @RegisterClass classes
// (Secure Web communication provider, eSignature drivers, server Actions).
import './mj-class-registrations.js';

// Explicit side-effect import of the server library — documents load order and guarantees
// the server package itself is pulled in alongside the manifest.
import '@mj-biz-apps/secure-messaging-server';

/**
 * Bootstrap function called by MJ server during dynamic package loading.
 * Registered via mj-app.json manifest: packages.server[].startupExport.
 *
 * Class registration is handled by the manifest import above (plus the server library
 * import), so all @RegisterClass classes are present without manual per-class loaders.
 */
export function LoadSecureMessaging(): void {
    LogStatus('MJ Secure Messaging: Server bootstrap loaded.');
}
